steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/movie-barcode-vis', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/movie-barcode-vis']
images:
  - 'gcr.io/$PROJECT_ID/movie-barcode-vis'
